compressionLevel: mixed

enableGlobalCache: false

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.2.cjs
